# Generated by Django 2.2.7 on 2019-12-03 22:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('formfile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_title',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
