# Generated by Django 2.2.7 on 2019-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfile_app', '0002_auto_20191203_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
