# Generated by Django 2.2.7 on 2019-12-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfile_app', '0003_auto_20191203_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='N/A', max_length=130),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='N/A', max_length=130),
        ),
    ]
